upstream proxy_backend {
    zone upstream-backend 10m;
    server 127.0.0.1:9080;
    server 127.0.0.1:9081;
    server 127.0.0.1:9082;
}


server {
    listen 10.31.78.18:9000;
    status_zone reverse_proxy; 
    server_name _;
    
    location / {
        proxy_pass http://proxy_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf)$ {
        proxy_pass http://127.0.0.1:9082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


}

}
  
}
