# Angiehasync configure file

    # Master node. Strictly speacking this node.
    M_NODE="10.31.78.22"

    # Dir to sync
    WATCH_DIR="/etc/angie/"

    LOG_FILE="/var/log/angiehasync/angiehasync.log"

    # Nodes should be listed with spaces as delimiter
    TARGET_HOSTS="10.31.78.18"

    ANGIE_RELOAD_TIMEOUT=5
    SYNC_TIMEOUT=2
    SSH_TIMEOUT=2
    SSH_PORT=22
    # Default SSH user is root
    SSH_USER="angie-ha-sync"
    # Path to Identity
    SSH_ID="/home/$SSH_USER/.ssh/id_rsa"
