server {
	
    listen 10.31.78.23:8099;
    
    location /console/ {

        auth_basic "Admin Area";
        auth_basic_user_file /etc/angie/.htpasswd;

        allow 10.103.252.0/24;
        allow 127.0.0.1;
        deny all;

        auto_redirect on;

        alias /usr/share/angie-console-light/html/;
        index index.html;

        location /console/api/ {
            api /status/;
        }

        # uncomment below lines to enable writable API
        # location /console/api/config/ {
        #     api /config/;
        # }
    }

}
