map $http_accept $img_ext {
        default "";

        ~*avif ".avif";
        ~*webp ".webp";
}

server {
	
    listen 10.31.78.18:8080;
    
    rewrite ^([^.]*[^/])$ $1/ permanent;

    location / {
        root /var/www/html/lesson5/ ;
	index index.html ;
	}

    location /images/ { 
        root /var/www/html/lesson5/images ;
	}
   
     location ~*\.(gif|jpg|jpeg|png) {
	root /var/www/html/lesson5/images;
	#root $static_root;
	} 

    location /yandex {
	return 301 https://ya.ru ;
	}
	
}

