server {
	
    listen 10.31.78.23:8099 ssl;
    http2 on;
    http3 on;
    status_zone balancer;
    server_name _;

    ssl_certificate /etc/angie/ssl/cert.crt;
    ssl_certificate_key  /etc/angie/ssl/cert_key.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers off;

    ssl_session_cache shared:SSL:20m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Alt-Svc 'h3=":443"; ma=86400' always;
    add_header Strict-Transport-Security max-age=31536000;

    location /console/ {

        auth_basic "Admin Area";
        auth_basic_user_file /etc/angie/.htpasswd;

        allow 10.103.252.0/24;
        allow 127.0.0.1;
        deny all;

        auto_redirect on;

        alias /usr/share/angie-console-light/html/;
        index index.html;

        location /console/api/ {
            api /status/;
        }

        # uncomment below lines to enable writable API
        # location /console/api/config/ {
        #     api /config/;
        # }
    }

}
