global_defs {
    enable_script_security
}

vrrp_script angie_check {
    script "/usr/bin/curl -s --connect-timeout 5 -A 'angie_hcheck_script' --no-buffer -XGET --unix-socket /tmp/angie_hcheck.sock http://hcheck/" 
    interval 5 
    user angie
}

vrrp_instance angie {
    state MASTER 
    interface ens33 
    virtual_router_id 254 
    priority 100 
    advert_int 2 unicast_src_ip 10.31.78.18

    unicast_peer {
        10.31.78.22
    }

    virtual_ipaddress {
        10.31.78.23
    } track_script {
        angie_check
    }
}
