upstream backend_rr {
    zone upstream-backend-rr 10m;
    server 127.0.0.1:9080;
    server 127.0.0.1:9081;
    server 127.0.0.1:9082 backup;
}

upstream backend_hash {
    zone upstream-backend-hash 10m;
    hash $remote_addr;
    server 127.0.0.1:9080;
    server 127.0.0.1:9081;
    server 127.0.0.1:9082;
}


upstream backend_random {
    zone upstream-backend-random 10m;
    random;
    server 127.0.0.1:9080;
    server 127.0.0.1:9081;
    server 127.0.0.1:9082;
}



server {
    listen 10.31.78.18:9100;
    status_zone balance-rr; 
    
    location / {
        proxy_pass http://backend_rr;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


}
  
}

server {
    listen 10.31.78.18:9101;
    status_zone balance-hash;

    location / {
        proxy_pass http://backend_hash;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


}

}

server {
    listen 10.31.78.18:9102;
    status_zone balance-random;

    location / {
        proxy_pass http://backend_random;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


}

}
